fix: global.codeceptjs is undefined
Creating a new test...
----------------------
? Feature which is being tested (ex: account, login, etc) rrrr
? Filename of a test rrrr_test.js

Could not load plugin allure from module 'allure-codeceptjs':
Cannot destructure property 'event' of 'global.codeceptjs' as it is undefined.
TypeError: Cannot destructure property 'event' of 'global.codeceptjs' as it is undefined.
    at Object.<anonymous> (/home/mmajorov/ttest/node_modules/allure-codeceptjs/dist/index.js:7:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)